# This is a basic workflow to help you get started with Actions

name: launch

# Controls when the workflow will run
on:
  schedule:
    - cron: "* */1 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "refresh"
  refresh:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Launch script
        run: |
          node src/index.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m"Calendar refresh."  || echo "No changes to commit"
          git push
