# This is a basic workflow to help you get started with Actions

name: launch

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  schedule:
    - cron: "* */1 * * *"
  workflow_dispatch:
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "refresh"
  refresh:
    # Don't run after github actions' pushes
    if: github.actor != 'github-actions'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.5"

      - name: Install dependencies
        run: |
          npm install
          python -m pip install -U pip setuptools
          python -m pip install -r requirements.txt

      - name: Download and convert URCA's XML calendar
        run: |
          python src/ipgp2ical.py "https://educatix.ipgp.fr/calendrier/2021-2022_bpsgnrg_BK/g34989.xml" > L1/IPGP.ical
          python src/ipgp2ical.py "https://educatix.ipgp.fr/calendrier/2021-2022_bpsgnrg_BK/g38350.xml" > L2/IPGP.ical

      - name: Download and agregate all iCals
        run: |
          node src/index.js

      - name: Commit & Push calendars
        run: |
          if git diff L1 L2 | grep . > /dev/null ; then
            git config --local user.name github-actions
            git config --local user.email "github-actions@github.com"
            git add L1 L2
            git commit -m "Calendar refresh" || echo "No changes to commit"
            git push
          fi
